### ISSUE TITLE
Checksum mismatch for GET API

### ISSUE THREAD

**Issue by sjain09** [Seagate/cortx-rgw#15] opened 2022-01-07 06:05 UTC
While doing a get call for an object I am getting “MD5 signatures do not match“ warning.

```
[root@ssc-vm-g3-rhev4-2880 build]# s3cmd --no-ssl put /boot/vmlinuz-4.18.0-348.2.1.el8_5.x86_64 s3://testbucket3/vmlinux
upload: '/boot/vmlinuz-4.18.0-348.2.1.el8_5.x86_64' -> 's3://testbucket3/vmlinux' [1 of 1]
10210440 of 10210440 100% in 0s 51.49 MB/s done
[root@ssc-vm-g3-rhev4-2880 build]# cd
[root@ssc-vm-g3-rhev4-2880 ~]# s3cmd --no-ssl get s3://testbucket3/vmlinux vmlinux
download: 's3://testbucket3/vmlinux' -> 'vmlinux' [1 of 1]
10210440 of 10210440 100% in 0s 134.52 MB/s done
WARNING: MD5 signatures do not match: computed=92326b2cc6b6898b4c3f238dff8c0b10, received=f9c5cc6840ab0093475b3b0699f4e58b
```

Initial analysis:

It looks like this is affected by some bs value as per the logs.

Below logs from the Nilesh's setup where bs value is more the the object size hence it is reading in one go.

```
2022-01-03T23:46:03.096-0700 7f910e311700 20 req 0 0.021999992s s3:get_obj open_mobj: rc=0
944 2022-01-03T23:46:03.098-0700 7f910e311700 15 req 0 0.023999993s Encryption mode:
945 2022-01-03T23:46:03.099-0700 7f910e311700 20 req 0 0.024999993s s3:get_obj MotrObject::read_mobj(): off=0 end=10210440
946 2022-01-03T23:46:03.099-0700 7f910e311700 20 req 0 0.024999993s s3:get_obj MotrObject::read_mobj(): bs=12582912
947 2022-01-03T23:46:03.099-0700 7f910e311700 20 req 0 0.024999993s s3:get_obj MotrObject::read_mobj(): off=0 actual=1021044 0
948 2022-01-03T23:46:03.099-0700 7f910e311700 20 req 0 0.024999993s s3:get_obj MotrObject::read_mobj(): init read op rc=0
949 2022-01-03T23:46:03.179-0700 7f910e311700 20 req 0 0.104999967s s3:get_obj MotrObject::read_mobj(): call cb to process d ata
```

Where as, on my setup bs value is less the object size hence it is reading object in two parts from the motr.

```
2022-01-03T23:44:31.501-0700 7feb36d33700 20 req 0 0.001000000s s3:get_obj MotrObject::read_mobj(): off=0 end=10210440
2022-01-03T23:44:31.501-0700 7feb36d33700 20 req 0 0.001000000s s3:get_obj MotrObject::read_mobj(): bs=8388608
2022-01-03T23:44:31.501-0700 7feb36d33700 20 req 0 0.001000000s s3:get_obj MotrObject::read_mobj(): off=0 actual=8388608
2022-01-03T23:44:31.502-0700 7feb36d33700 20 req 0 0.002000001s s3:get_obj MotrObject::read_mobj(): init read op rc=0
2022-01-03T23:44:31.532-0700 7feb36d33700 20 req 0 0.032000020s s3:get_obj MotrObject::read_mobj(): call cb to process data
2022-01-03T23:44:31.536-0700 7feb36d33700 20 req 0 0.036000025s s3:get_obj MotrObject::read_mobj(): off=8388608 actual=1821832
2022-01-03T23:44:31.536-0700 7feb36d33700 20 req 0 0.036000025s s3:get_obj MotrObject::read_mobj(): init read op rc=0
2022-01-03T23:44:31.557-0700 7feb36d33700 20 req 0 0.057000041s s3:get_obj MotrObject::read_mobj(): call cb to process data
2022-01-03T23:44:31.559-0700 7feb36d33700 2 req 0 0.059000041s s3:get_obj completing
```

This is happening because currently we are not properly handling the case when object is read in multiple iterations from the motr depending on the optimal block size that can read at once from the motr.

**Comment by cortx-admin** [comment] 2022-02-17 02:48
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-28852. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment] 2022-02-23 06:57
> Saurabh Jain commented in Jira Server:

This is a duplicate of https://jts.seagate.com/browse/CORTX-27698.

Closing this ticket.

**Comment by cortx-admin** [comment] 2022-03-16 05:45
> Saurabh Jain commented in Jira Server:

Already resolved by CORTX-27698.

**Comment by cortx-admin** [comment] 2022-03-16 05:45
> Saurabh Jain commented in Jira Server:

Fixed in CORTX-27698.

**Closed by cortx-admin** 2022-03-16 05:45 UTC

**Comment by cortx-admin** [comment] 2022-03-16 08:42
> Donald R Bloyer commented in Jira Server:

[~747271] [~744427] [~720600] [~936756]

So who is responsible for closing Boardgenius issues?

**Comment by cortx-admin** [comment] 2022-03-16 10:39
> Mukul Malhotra commented in Jira Server:

.
