### ISSUE TITLE
Watch-notify mechanism for metadata cache to be supported

### ISSUE THREAD

**Issue by siningwuseagate** [Seagate/cortx-rgw#14] opened 2022-01-05 17:04 UTC
Currently the metadata cache is implemented based on expiry time. There exists a window in which an object has been updated (for example, resized, deleted etc. ) but the cached metadata items in other instances haven't expired yet, resulting invalid metadata been returned. Watch-notify is to register a callback function (watch) on an object, when there is any update on the watched object in one rgw instance, a notification will be sent to other instances to update corresponding cache items. Motr FDMI will be explored to implement this watch-notify mechanism. 

There may be other user cases for watch-notify mechanism.

**Comment by cortx-admin** [comment] 2022-02-17 02:48
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-28851. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment] 2022-05-25 07:02
> Amit Kapil commented in Jira Server:

This is not a bug. Please assign the right epic for this requirement. Discuss with Basav and Ujjwal for the feature epic Jira.

**Comment by shailesh-vaidya** [comment] 2024-02-08 17:03
Closing as an obsolete

**Closed by shailesh-vaidya** 2024-02-08 17:03 UTC
Labels: Status: Backlog, Status: L2 Triage, Triage:DevTeam, Patrick
