### ISSUE TITLE
Reading beyond object end triggers degraded read

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-rgw#216] opened 2022-05-21 09:08 UTC
Let's create 200M object and try to read it back:

```
[root@ssc-vm-g4-rhev4-1490 ~]# aws s3api put-object --bucket test-bucket --key 200m-2 --body /tmp/200m --endpoint-url http://192.168.60.187:30080
{
    "ETag": "\"d7788d7d30a34de87f033012cf97834d\""
}
[root@ssc-vm-g4-rhev4-1490 ~]# aws s3api get-object --bucket test-bucket --key 200m-2 /tmp/200m.check --endpoint-url http://192.168.60.187:30080
motr[00001]:   850  ERROR  [fd/fd.c:425:tolerance_check]  <! rc=-22
motr[00001]:  42c0  ERROR  [io_req_fop.c:364:io_bottom_half]  ioo=0x55f53543e000 off=209715200 pg=18446744073709551615 from=inet:tcp:cortx-data-headless-svc-ssc-vm-g4-rhev4-1491@21001 rc=-5 ti_rc=-5 @<4300000806aa107d:466000008800002>
motr[00001]:  43d0   WARN  [io_req.c:1645:ioreq_dgmode_read]  Process failed parity groups in dgmode/read ioo=0x55f53543e000 dgmap_nr=8
{
    "AcceptRanges": "bytes",
    "LastModified": "Sat, 21 May 2022 09:01:51 GMT",
    "ContentLength": 209715200,
    "ETag": "\"d7788d7d30a34de87f033012cf97834d\"",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
```

We can see that we try to read all units in the last parity group which are beyond the end of the object. As a result, we get EIO error and switch to regraded mode.

Sometimes, such behaviour may end up in inability to read the object at all (when we cannot read parity units for some reason), see https://github.com/Seagate/cortx-motr/issues/1789#issuecomment-1133564352.

Suggested possible solutions: 1) use `M0_OOF_HOLE` flag when reading beyond the end of the object or, 2) don't read beyond the end at all. (2nd variant is preferable, as it's more optimal for the i/o - fewer fops are sent to the motr servers, less network bandwidth is used, etc.).

Versions:
```
[root@ssc-vm-g4-rhev4-1490 ~]# kubectl exec -it cortx-server-ssc-vm-g4-rhev4-1490-856cf6d66b-bc26l -c cortx-rgw -- rpm -qa | grep cortx
cortx-rgw-integration-2.0.0-6220_077adb5.noarch
cortx-motr-2.0.0-6220_git41353fb.el8.x86_64
cortx-provisioner-2.0.0-6220_6a38c7d6.noarch
cortx-py-utils-2.0.0-6220_f0191fc0.noarch
cortx-hare-2.0.0-6220_gitbfca810.el8.x86_64
```

Note: the printout of motr warnings/errors from all rgw instances into the console was enabled like this: `kubectl get pods | grep x-server | awk '{print $1}' | while read p; do kubectl logs $p -c cortx-rgw -f & done`.

**Comment by cortx-admin** [comment] 2022-05-21 09:08
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31567. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by cortx-admin** [comment] 2022-05-22 09:47
> Chandradhar Raval commented in Jira Server:

Hi [~744292],

Degraded read is not working on latest main. There are two Motr PRs [1803|https://github.com/Seagate/cortx-motr/pull/1803] and [1792|https://github.com/Seagate/cortx-motr/pull/1792] which fixes the same.

Team tested Custom build [https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6219/] which was tested fine.

The scenario mentioned by [~520414] in this Jira is to be fixed by RGW team

Can we prioritize this issue for Degraded read failure?

cc : [~211146], [~520423]

**Comment by cortx-admin** [comment] 2022-05-23 02:55
> Amit Kapil commented in Jira Server:

[~936756] and [~744293] Can you review the scenario Andriy T has mentioned and how much work that will be for RGW team. We can review and discuss when can we do this in the meeting.

**Comment by cortx-admin** [comment] 2022-05-23 05:04
> Chandradhar Raval commented in Jira Server:

Based on discussion with RGW team, we plan to explore below solution from RGW side : 
 # GET operation - RGW side we don't try to read beyond the object size 
 # Fix rgw code to use {{M0_OOF_HOLE}} flag when it tries to read beyond the object size 

Note : Please use Motr branch "dgmod-no-dtm" while testing above fixes(This includes required Motr PRs 1803 & 1792)

**Comment by andriytk** [comment] 2022-05-23 08:56
> GET operation - RGW side we don't try to read beyond the object size

Yes, you do: https://github.com/Seagate/cortx-rgw/blob/ec168cc55bcb6f3b882199efda8fe820e1cb4159/src/rgw/rgw_sal_motr.cc#L2148

and: https://github.com/Seagate/cortx-rgw/blob/ec168cc55bcb6f3b882199efda8fe820e1cb4159/src/rgw/rgw_sal_motr.cc#L2138

Note: `get_optimal_bs()` rounds up `bs` to the parity group size.

**Comment by cortx-admin** [comment] 2022-05-24 04:11
> Amit Kapil commented in Jira Server:

This will be resolved with new story [CORTX-31575] Improve read function to handle object writing with M0_ENF_NO_RMW flag - JIRA NSS (seagate.com)

**Comment by cortx-admin** [comment] 2022-05-24 04:11
> Amit Kapil commented in Jira Server:

[CORTX-31575] Improve read function to handle object writing with M0_ENF_NO_RMW flag - JIRA NSS (seagate.com)

**Comment by cortx-admin** [comment] 2022-05-24 04:11
> Amit Kapil commented in Jira Server:

This is duplicate of the work [CORTX-31575] Improve read function to handle object writing with M0_ENF_NO_RMW flag - JIRA NSS (seagate.com)

**Closed by cortx-admin** 2022-05-24 04:11 UTC
Labels: IOstability

**Comment by andriytk** [comment] 2022-05-25 14:43
Fixed by https://github.com/Seagate/cortx-rgw/pull/217.

**Comment by cortx-admin** [comment] 2022-05-30 06:44
> Kapil Jinna commented in Jira Server:

Verified this ticket as part of testing done in https://jts.seagate.com/browse/CORTX-31575

Hence closing this ticket.
